### ISSUE TITLE
Present ImagePicker Can Be Slow 

### ISSUE THREAD

**Issue by IceFireCreations** [hyperoslo/ImagePicker#229] opened 2016-11-01 12:52 UTC
If there an option or setting I am missing?

**Comment by RamonGilabert** [comment] 2016-11-01 18:17
Can you provide more information?

**Comment by IceFireCreations** [comment] 2016-11-01 19:52
Sure when using latest pod image piker loads fine with self.present but when updating pod to match latest commit so camera can load at front sel.present takes about 3 to 4 seconds

**Comment by aashishdhawan** [comment] 2017-01-02 07:17
This is a duplicate of #243. Closing this, in order to keep issues list clean.

**Closed by aashishdhawan** 2017-01-02 07:17 UTC
