### ISSUE TITLE
Captured images doesn't respect orientation

### ISSUE THREAD

**Issue by everlof** [hyperoslo/ImagePicker#211] opened 2016-09-25 17:07 UTC
Using Image Picker 1.4.0, iOS 10, iPhone 6.

The images that are captured and then used are saved as portrait images instead of landscape (in the camera roll as well).

My app only allows portrait (but that shouldn't be a problem since it detects the orientation and rotates when I rotate).

**Comment by onmyway133** [comment] 2016-09-25 20:13
@everlof Hi, it could be the same with this https://github.com/hyperoslo/ImagePicker/issues/187
In the mean time, can you point to `master` (in your Podfile) and see if the problem is fixed for you?

**Comment by everlof** [comment] 2016-09-26 04:53
I can confirm that images now are captured correctly (running from master)! 👍

**Comment by RamonGilabert** [comment] 2016-09-26 07:37
Yay! We'll have to release a new version, but closing for now! :)

**Closed by RamonGilabert** 2016-09-26 07:37 UTC

**Comment by onmyway133** [comment] 2016-09-26 07:42
@everlof @RamonGilabert yeah, version 1.4.1 is out

**Comment by rx2130** [comment] 2016-10-19 23:19
I'm also having the same problem running the latest `master` on iPhone 6s and iPhone 6 plus on iOS 10.

When the portrait lock is on, then taking a photo in the imagePicker in landscape mode, the image captured/saved is not in landscape mode. ImagePicker only rotate when portrait lock is off.

This is somewhat counter-intuitive since people expect camera to behave like default iOS camera that rotate automatically regardless of portrait lock status. Is there someway we would capture the landscape mode properly?

**Comment by filipandrei87** [comment] 2016-11-24 14:38
Can confirm that having the orientation lock on, it doesn't rotate. Would be nice to have.
